# Standards: 0.1
---
- name: Fact appcleaner user
  set_fact:
    appcleaner_user: "{{ appcleaner_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - appcleaner

- become: "{{ (appcleaner_user != ansible_user_id) | bool }}"
  become_user: "{{ appcleaner_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: appcleaner
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - appcleaner

- name: Remove quarantine flag
  register: appcleaner_quarantine
  failed_when: appcleaner_quarantine.rc != 0 and "No such xattr" not in appcleaner_quarantine.stderr
  changed_when: appcleaner_quarantine.rc == 0
  command: xattr -d com.apple.quarantine /Applications/AppCleaner.app
  tags:
    - appcleaner

...
